# -*- coding: utf-8 -*-
"""CIND830_Summer22_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_DaMAZUNfwJRO_F7xzcceOc54HXWrOD

## CIND830 - Python Programming for Data Science  
### Assignment 1 (10% of the final grade) 
### Due on July 11, 2022 11:59 PM 
### Section DHB | Student Number: 500778806

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF. Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebooks.

Consider using a Jupyter Notebook platform to complete this assignment. Ensure using **Python 3.7 release or higher** then complete the assignment by inserting your Python code wherever seeing the string `#INSERT YOUR ANSWER HERE.`

When you click the `File` button, from the top navigation bar, then select `Export Notebook to HTML`, an HTML document will be generated that includes both the assignment content and the output of any embedded Python code chunks.

Use [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines to submit **both** the IPYNB and the exported file (HTML). Failing to submit both files will be subject to mark deduction.

Please be advised that you cannot get more than 100% in this assignment, and the **BONUS** question (if there is any) will only be graded if all other questions have been submitted.

*****

### **Question 1  [25 pts]**:

According to the Toronto Real Estate Trends and the Housing Market Report for June 2022 (published in https://www.zolo.ca/toronto-real-estate/trends) in June 2022, the average house price in GTA decreased to $1,187,564 in June 2022 with a month-to-month change rate of -4.7 percent. As of June 2022, Toronto housing data shows median days on market for a home is 14 days.

```
regionName = "Greater Toronto Area"
juneAvePrice = 1187564
changeRate = -0.047
daysInMarket = 14
decreasing = True
```

**a) [5 pts]**  Use the built-in `print()` function to display the literal and type of the five variables listed above.
"""

# INSERT YOUR ANSWER HERE
regionName = "Greater Toronto Area"
juneAvePrice = 1187564
changeRate = -0.047
daysInMarket = 14
decreasing = True
print(type(regionName))
print(type(juneAvePrice))
print(type(changeRate))
print(type(daysInMarket))
print(type(decreasing))

"""**b) [5 pts]**  Suppose that the decrease rate stays the same in July 2022. Compute and display the new expected Average Selling Price for this month, and round up the result to the nearest whole number."""

# INSERT YOUR ANSWER HERE
julyAvePrice = juneAvePrice - (juneAvePrice*0.047)
print(julyAvePrice)

"""**c) [5 pts]**  Compute and display the difference between the Average Selling Price in June 2022 and that in July 2022."""

# INSERT YOUR ANSWER HERE
diffAvePrice = juneAvePrice - julyAvePrice
print(diffAvePrice)

"""**d) [5 pts]**  Convert the variable `junAvePrice` to a floating-point number
then display the new literal and type.
"""

# INSERT YOUR ANSWER HERE
juneAvePrice = float(juneAvePrice)
print(type(juneAvePrice))

"""**e) [5 pts]**  Given that `var1` is the `julyAvePrice` variable rounded up to the nearest whole number,
and `var2` is the `changeRate` variable rounded to two decimal places.

Print the following statement:
The average selling price might be `var1` in July 2022, which is a `var2` month-to-month change rate.
"""

# INSERT YOUR ANSWER HERE
var1 = round(julyAvePrice, 2)
var2 = round(changeRate, 2)
print("The average selling price might be " + str(var1) + " in July 2022, which is a " + str(var2) + " month-to-month change rate.")

"""*****

### Question 2  **[35 pts]**:

**a) [15 pts]**  Write a Python program that accepts a list of marks then prints the letter grade and description according to the [Grading System](https://continuing.ryerson.ca/contentManagement.do?method=load&code=CM000034) of the Chang School of Continuing Education.

For example, if the user enters `90, 120, -12, 71.5, 62.5`, the output would be as follows:

| Mark | Letter Grade | Performance Description |
|:-:|:-:|:-:|
| 90 | A+ | Excellent |
| 120 | Not Possible | Not Possible |
| -12 | Not Possible | Not Possible |
| 71.5 | B- | Good |
| 62.5 | C | Satisfactory |
"""

# INSERT YOUR ANSWER HERE
number = float(input("Enter the numeric grade: "))
if number >= 90 or number <= 100:
  letter = 'A+',
  performance = "Excellent"
elif number >= 85 or number <= 89:
  letter = 'A'
  performance = "Excellent"
elif number >= 80 or number <= 84:
  letter = 'A-'
  performance = "Excellent"
elif number >= 77 or number <= 79:
  letter = 'B+'
  performance = "Good"
elif number >= 73 or number <= 76:
  letter = 'B'
  performance = "Good"
elif number >= 70 or number <= 72:
  letter = 'B-'
  performance = "Good"
elif number >= 67 or number <= 69:
  letter = 'C+'
  performance = "Satisfactory"
elif number >= 63 or number <= 66:
  letter = 'C'
  performance = "Satisfactory"
elif number >= 60 or number <= 62:
  letter = 'C-'
  performance = "Satisfactory"
elif number >= 57 or number <= 59:
  letter = 'D+'
  performance = "Marginal"
elif number >= 53 or number <= 56:
  letter = 'D'
  performance = "Marginal"
elif number >= 50 or number <= 52:
  letter = 'D-'
  performance = "Marginal"
else:
  letter = 'F'
  performance = "Not Possible"
print("The letter grade is", letter, "and the performance description is", performance)

"""**b)**  **[10 pts]** Write a code to compute and print the sum of squares of only the `Excellent` marks.

For example, if the user enters `90.5, 120, -12, 71.3, 82.2, 62.5`, then the output should be: <br>
`The Excellent marks are:  90.5, 82.2`<br>
`The sum of squares is  14947.09`
"""

# INSERT YOUR ANSWER HERE
# Creating an empty list
numbersList = []
# Elements as input
numbersList = [float(number) for number in input("Enter the numeric grades : ").split(',')]
excellentNumbers = [number for number in numbersList if number >= 80]
# Sum of squares
theSum = 0
theSum = sum([number**2 for number in excellentNumbers])
print("The excellent numbers are", excellentNumbers)
print("The sum of squares is", theSum)

"""**c)**  **[10 pts]** Write a code to compute and print the `Median`, `Average` and `Variance` of the marks between 0 and 100, inclusively, after rounding each mark to the nearest integer.

For example, if the user enters `59.8, 60, 29.5, 30, 50, 200`, then the output should be: <br>
`The valid marks are:  60, 60, 30, 30, 50 `<br>
`Median is 50 ; Average is 46 ; Variance is 230`

Hint: Use the [statistics](https://docs.python.org/3.8/library/statistics.html) module as it provides functions to calculate mathematical statistics of numeric data.
"""

# INSERT YOUR ANSWER HERE
import statistics
# Creating an empty list
numbersList = []
# Elements as input
numbersList = [float(number) for number in input("Enter the numeric grades : ").split(',')]
entryNumbers = [number for number in numbersList if number <= 100]
# Calculations
medianNumbers = statistics.median(entryNumbers)
avgNumbers = statistics.mean(entryNumbers)
varNumbers = statistics.variance(entryNumbers)
roundedEntryNumbers = [round(number) for number in entryNumbers]
print("The valid marks are:", roundedEntryNumbers)
print("the Median is", round(medianNumbers), "; Average is", round(avgNumbers), "; Variance is", round(varNumbers))

"""****

### Question 3  **[40 pts]**:
Write a program that accepts the lengths of three sides of a triangle as inputs then prints the type and compute the properties of the triangle according to the listed conditions and mathematical formulae.

**a)**  **[20 pts]** Ensure that all side lengths are positive and the sum of any two side lengths is greater than the third side length.
"""

# INSERT YOUR ANSWER HERE
# Ensure triangle validity
a = int(input("Enter the length of the first side:"))
b = int(input("Enter the length of the second side:"))
c = int(input("Enter the length of the third side:"))
def triangle(a,b,c):      
 if(a + b > c) and ( b + c > a) and (a + c > b):     
   print("Yes")
 else:
   print("No")
triangle(a,b,c)

"""**b)**  **[20 pts]** Display the type of the triangle according to the following restrictions:

Equilateral Triangle: If the triangle has three congruent sides.

Isosceles Triangle: If the triangle has two equal sides.
 
Scalene Triangle: If the triangle has no congruent sides, and each side have a different length.
 
Right Triangle: If the square of one side equals the sum of the squares of the other
two sides.
"""

# INSERT YOUR ANSWER HERE
# This is the first method. It will loop until the program accepts the side lengths
while True: 
  a = int(input("Enter the length of the first side:"))
  b = int(input("Enter the length of the second side:"))
  c = int(input("Enter the length of the third side:"))     
  if (a + b > c) and ( b + c > a) and (a + c > b):
    print("This is a triangle.")     
    break
    print("This is not a triangle")
# Conditions for type of triangle
if (a == b) and (a == c):
  print("This is an equilateral triangle. It has three congruent sides.")
elif (a == b) or (a == c):
  print("This is an isosceles triangle. It has two equal sides.")
elif (a != b) and (a != c) and (b != c):
  print("This is a scalene triangle. It has no congruent sides and each side has a different length.")
elif (a**2 + b**2 == c**2) or (c**2 + b**2 == a**2) or (a**a + c**2 == b**2):
  print("This is a right triangle. It has the square of one side equals the sum of the squares of the other two sides.")
else:
  print('Error')

# This is an alternate method. It correctly identifies whether it is a triangle and the type but will pass through the first condition even if it is not a triangle
a = int(input("Enter the length of the first side:"))
b = int(input("Enter the length of the second side:"))
c = int(input("Enter the length of the third side:"))
def triangle(a,b,c):      
 if(a + b > c) and ( b + c > a) and (a + c > b):     
   print("This is a triangle")
 else:
   print("This is not a triangle")
triangle(a,b,c)
# Conditions for type of triangle
if (a == b) and (a == c):
  print("This is an equilateral triangle. It has three congruent sides.")
elif (a == b) or (a == c):
  print("This is an isosceles triangle. It has two equal sides.")
elif (a != b) and (a != c) and (b != c):
  print("This is a scalene triangle. It has no congruent sides and each side has a different length.")
elif (a**2 + b**2 == c**2) or (c**2 + b**2 == a**2) or (a**a + c**2 == b**2):
  print("This is a right triangle. It has the square of one side equals the sum of the squares of the other two sides.")
else:
  print('Error')

"""#### This is the end of assignment 1"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# jupyter nbconvert -- to html /content/CIND830_Summer22_Assignment1.ipynb